import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-webhook',
  templateUrl: './webhook.component.html',
  styleUrls: ['./webhook.component.scss']
})
export class WebhookComponent implements OnInit {

  webhooks = [
    {
      organization: 'built-in',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '	2021-12-26 20:30:08',
    },
    {
      organization: 'built-in2',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '2022-10-20 14:54:00',
    },
    {
      organization: 'built-in',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '	2021-12-26 20:30:08',
    },
    {
      organization: 'built-in2',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '2022-10-20 14:54:00',
    },
    {
      organization: 'built-in',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '	2021-12-26 20:30:08',
    },
    {
      organization: 'built-in2',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '2022-10-20 14:54:00',
    },
    {
      organization: 'built-in',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '	2021-12-26 20:30:08',
    },
    {
      organization: 'built-in2',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '2022-10-20 14:54:00',
    },
    {
      organization: 'built-in',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '	2021-12-26 20:30:08',
    },
    {
      organization: 'built-in2',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '2022-10-20 14:54:00',
    },
    {
      organization: 'built-in',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '	2021-12-26 20:30:08',
    },
    {
      organization: 'built-in2',
      name: '	webhook_hasura',
      url: 'http://localhost:10000/webhook',
      method: 'POST',
      content_type: 'application/json',
      events: ['signup', 'login', 'logout', 'update-user'],
      is_user_extended: false,
      is_enabled: 'false',
      created_at: '2022-10-20 14:54:00',
    },
  ];
  constructor() { }

  ngOnInit(): void {
  }

}
