import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-resources',
  templateUrl: './resources.component.html',
  styleUrls: ['./resources.component.scss']
})
export class ResourcesComponent implements OnInit {

  resources = [
    {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    }, {
      privder: 'privder_storage_aliyun_oss',
      application: 'app-built-in',
      user: 'yoyo314',
      parent: 'ResourceListPage',
      name: '/casdoor/resource/casbin/yoyo314/%E6%8F%92%E5%9B%BE2.png',
      created_at: '2021-12-26 20:30:08',
      tag: 'custom',
      type: 'image',
      format: '.png',
      file_size: '34.9 KB',
      preview: '',
      url: 'https://www.google.com.tw/',
    },
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
