import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.scss']
})
export class UsersComponent implements OnInit {

  users = [
    {
      organization: 'YG',
      application: 'app-yg',
      name: 'JennieRubyJane',
      creat_time: '2021-12-26 20:30:08',
      display_name: 'Jennie',
      avatar: '',
      email: 'admin@gmail.com',
      phone: '0800092000',
      affiliation: '高雄科技大學',
      country_region: '中華民國',
      tag: 'idol',
      is_admin: true,
      is_global_admin: true,
      is_foribidden: false,
      is_delete: false,
    },
    {
      organization: 'YG',
      application: 'app-yg',
      name: 'Lisa',
      creat_time: '2021-12-26 20:30:08',
      display_name: 'Admin',
      avatar: '',
      email: 'admin@gmail.com',
      phone: '0800092000',
      affiliation: '高雄科技大學',
      country_region: '中華民國',
      tag: 'idol',
      is_admin: true,
      is_global_admin: true,
      is_foribidden: false,
      is_delete: false,
    },
    {
      organization: 'YG',
      application: 'app-yg',
      name: 'Rose',
      creat_time: '2021-12-26 20:30:08',
      display_name: 'Admin',
      avatar: '',
      email: 'admin@gmail.com',
      phone: '0800092000',
      affiliation: '高雄科技大學',
      country_region: '中華民國',
      tag: 'idol',
      is_admin: true,
      is_global_admin: true,
      is_foribidden: false,
      is_delete: false,
    },
    {
      organization: 'YG',
      application: 'app-yg',
      name: 'Jisoo',
      creat_time: '2021-12-26 20:30:08',
      display_name: 'Admin',
      avatar: '',
      email: 'admin@gmail.com',
      phone: '0800092000',
      affiliation: '高雄科技大學',
      country_region: '中華民國',
      tag: 'idol',
      is_admin: true,
      is_global_admin: true,
      is_foribidden: false,
      is_delete: false,
    },
    {
      organization: 'hype',
      application: 'app-hype',
      name: 'V',
      creat_time: '2021-12-26 20:30:08',
      display_name: 'Admin',
      avatar: '',
      email: 'admin@gmail.com',
      phone: '0800092000',
      affiliation: '高雄科技大學',
      country_region: '中華民國',
      tag: 'student',
      is_admin: false,
      is_global_admin: false,
      is_foribidden: false,
      is_delete: false,
    },
    {
      organization: 'JYP',
      application: 'app-jyp',
      name: '周子瑜',
      creat_time: '2021-12-26 20:30:08',
      display_name: 'Admin',
      avatar: '',
      email: 'admin@gmail.com',
      phone: '0800092000',
      affiliation: '高雄科技大學',
      country_region: '中華民國',
      tag: 'student',
      is_admin: false,
      is_global_admin: false,
      is_foribidden: false,
      is_delete: false,
    },
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
